POST http://localhost:3030/login HTTP/1.1
Content-Type: application/json

{
  "email": "facundoduran31@gmail.com",
  "password": "admi"
}

###

POST http://localhost:3030/registrar HTTP/1.1
Content-Type: application/json

{
  "nombreApellido": "Facundo Duran",
  "password": "admin",
  "numeroLegajo": "92361",
  "email": "facundoduran31@gmail.com"
}

###
PUT http://localhost:3030/laboratorios/18 HTTP/1.1
Content-Type: application/json

{
  "nombre": "prueba"
}


###

GET http://localhost:3030/ HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZhY3VuZG9kdXJhbjMxQGdtYWlsLmNvbSIsImlhdCI6MTY3ODA0MTgyNywiZXhwIjoxNjc4MDQ1NDI3fQ.1KtrnhAJUjfM640PT0AsN1I7ELcAfxRaMa